# Generated by Django 2.0.5 on 2018-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180507_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='docs_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
